reorder_imports = true
imports_granularity = "Crate"
unstable_features = true
max_width = 85
wrap_comments = true
empty_item_single_line = false
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
